main: async_server_with_work_queue.cpp
	g++ async_server_with_work_queue.cpp -o main -lcppnetlib-uri -lboost_system -lpthread -lboost_thread  -lcppnetlib-server-parsers -std=c++11 -Wall

clean:
	rm -rf main
